// Code generated by MockGen. DO NOT EDIT.
// Source: ./uuid.go

// Package uuid is a generated GoMock package.
package uuid

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUUID is a mock of UUID interface.
type MockUUID struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDMockRecorder
}

// MockUUIDMockRecorder is the mock recorder for MockUUID.
type MockUUIDMockRecorder struct {
	mock *MockUUID
}

// NewMockUUID creates a new mock instance.
func NewMockUUID(ctrl *gomock.Controller) *MockUUID {
	mock := &MockUUID{ctrl: ctrl}
	mock.recorder = &MockUUIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUID) EXPECT() *MockUUIDMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockUUID) New(prefix ...string) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range prefix {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockUUIDMockRecorder) New(prefix ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockUUID)(nil).New), prefix...)
}
